### PR TITLE
DOCSP-26952 standardize on ID

### PR DESCRIPTION
**Pull request by davemungo**
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-26952-standardize-on-ID/style-guide/style/capitalization/#capitalize-most-abbreviations)

[JIRA](https://jira.mongodb.org/browse/DOCSP-26952)

The guide for ID usage was already there. Added a few lines to make it more discoverable.

### CODE REVIEW

**Comment by davemungo** [comment]
@jeff-allen-mongo  Tagging you as the style guide rep as per the wiki. Let me know if this you go to someone else.

**Review by krollins-mdb — APPROVED** [review]
LGTM! Thanks for making this convention clearer.

**Review by ccho-mongodb — APPROVED** [review]
LGTM

**Review by corryroot — APPROVED** [review]
LGTM

**Comment by jeff-allen-mongo** [comment]
A question regarding our usage of ID / _id:

We use `_id` to refer to a document's _id field, which contains the document's unique identifier. I believe we explicitly _do not_ want to capitalize `_id` in this context, because it's not how it appears in the document / in the user's code. I wonder if that's worth clarifying as part of this update, either by:

- Adding another row to this table for `_id`
- Adding a clarifying sentence to the newly added "ID" row that this does not apply to document identifier fields.

Curious for others' thoughts here.

**Comment by ccho-mongodb** [comment]
> * Adding another row to this table for `_id`
> * Adding a clarifying sentence to the newly added "ID" row that this does not apply to document identifier fields.
> 
> Curious for others' thoughts here.

Either of these seems reasonable to add for clarity since it's possible someone might conflate the two.

**Comment by davemungo** [comment]
_id isn't an abbreviation, it shouldn't be a row in a table which lists abbreviations. 

A note doesn't seem necessary, "_id" isn't used the same way as "ID". The underscore already signals that it is a different "word".

**Comment by jeff-allen-mongo** [comment]
I see this as a potential ambiguity that the style guide is designed to clarify. I can envision a situation where a new writer without prior knowledge of MongoDB would benefit from an explicit mention that document _id is different from ID. However, if you feel strongly that this isn't necessary I'm ok to sign off on this as-is.

**Review by jeff-allen-mongo — APPROVED** [review]

**Comment by jeff-allen-mongo** [comment]
@davemungo thanks for the update.

**Pull request merged**
