### PR TITLE
(DOCSP-27404): Update VS Code snooty installation instructions

### PR DESCRIPTION
**Pull request by pierwill**
[JIRA](https://jira.mongodb.org/browse/DOCSP-27404)

[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/pierwill-patch-2-snooty/style-guide/)

Also add a TOC entry.

### CODE REVIEW

**Comment by corryroot** [comment]
@ccho-mongodb, any idea why this still isn't staging and appearing in the TOC?

**Review by corryroot — APPROVED** [review]
LGTM.

**Review by ccho-mongodb — APPROVED** [review]
LGTM

**Review by jeff-allen-mongo — APPROVED** [review]
LGTM

**Review by krollins-mdb — APPROVED** [review]
LGTM

**Pull request merged**
