### PR TITLE
Action-oriented TOC labels

### PR DESCRIPTION
**Pull request by mongoKart**
# Pull Request Process

Please read the
[Style Guide Review Process](https://wiki.corp.mongodb.com/display/DE/Technical+Writer+Style+Guide+Review+Process)
wiki page.

Contributors should take the following actions:

- Request a PR review in #docs-style-guide Slack channel.
- Add the Style Guide team reps as reviewers.
- If any reviewer requests changes, address them and request another review.
- When you receive PR review approvals from all the Style Guide team reps,
  they will merge the PR and notify you of the merge in the Slack channel.

# Pull Request Description

Add guidance about using action-oriented TOC labels.

### CODE REVIEW

**Review by stephmarie17 — APPROVED** [review]
LGTM!

**Review by lindseymoore — APPROVED** [review]
Text LGTM! I see deploy is failing though, does paragraph spacing work for bullet point format?

**Comment by corryroot** [comment]
> Text LGTM! I see deploy is failing though, does paragraph spacing work for bullet point format?

@lindseymoore, should work. Might just need a redeploy...

**Comment by mongoKart** [comment]
> > Text LGTM! I see deploy is failing though, does paragraph spacing work for bullet point format?
> 
> @lindseymoore, should work. Might just need a redeploy...

Yep, seems to be working now.

**Review by jeff-allen-mongo — APPROVED** [review]
LGTM, thanks for this update!

**Pull request merged**
