### PR TITLE
DOCS-16441 Add Rendered Icon Table

### PR DESCRIPTION
**Pull request by ianf-mongodb**
# Pull Request Process

Please read the
[Style Guide Review Process](https://wiki.corp.mongodb.com/display/DE/Technical+Writer+Style+Guide+Review+Process)
wiki page.

Contributors should take the following actions:

- Request a PR review in #docs-style-guide Slack channel.
- Add the Style Guide team reps as reviewers.
- If any reviewer requests changes, address them and request another review.
- When you receive PR review approvals from all the Style Guide team reps,
  they will merge the PR and notify you of the merge in the Slack channel.

# Pull Request Description

<Optional summary of changes>

This PR adds a table on the icon page with all icons that are available in snooty, along with the syntax and rendered output. 

JIRA URL: https://jira.mongodb.org/browse/DOCS-16441

Staging URL: https://preview-mongodbianfmongodb.gatsbyjs.io/meta/DOCS-16441/reference/icon/#rendered-icon-table

Build Log: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=656785137a5cb5fef5436a6e

### CODE REVIEW

**Comment by ianf-mongodb** [comment]
Build Errors:

ERROR(style-guide/includes/rendered-icon-table.rst:40ish): The Icon lg-Colon does not exist
ERROR(style-guide/includes/rendered-icon-table.rst:44ish): The Icon lg-Gauge does not exist
ERROR(style-guide/includes/rendered-icon-table.rst:216ish): The Icon lg-TimeSeriesCollection does not exist
ERROR(style-guide/includes/rendered-icon-table.rst:552ish): The Icon lg-Cursor does not exist
ERROR(style-guide/includes/rendered-icon-table.rst:6268ish): The Icon mms-icon-org-icon-activity-feed does not exist
ERROR(style-guide/includes/rendered-icon-table.rst:7268ish): The Icon fa-icon-geoglobe does not exist

**Review by ccho-mongodb — APPROVED** [review]
Approving, but have a few suggestions:

1.
I checked this on the lynx terminal browser to verify the claim that it generates a caption, but it only appears to omit the content.
E.g. 
```
   Press the button.

   Press the key. This has the caption Windows logo.
```

While not part of the changes you made, the reader might be misled that it provides captions for no-CSS browsers.
I think a platform ticket should be created if rendering an alt tag or caption is the expected behavior.

2.
I think >20 of the icons show up as blank such as "fa-creative-commons-sampling", "fa-slack", etc.

3.
I think providing a link to the script to generate the icon table in an rST comment could be helpful if the list needs to be generated again.

**Comment by ianf-mongodb** [comment]
> Approving, but have a few suggestions:
> 
> 
> I checked this on the lynx terminal browser to verify the claim that it generates a caption, but it only appears to omit the content. E.g.
> 
> ```
>    Press the button.
> 
>    Press the key. This has the caption Windows logo.
> ```
> 
> While not part of the changes you made, the reader might be misled that it provides captions for no-CSS browsers. I think a platform ticket should be created if rendering an alt tag or caption is the expected behavior.
> 
> 
> I think >20 of the icons show up as blank such as "fa-creative-commons-sampling", "fa-slack", etc.
> 
> 
> I think providing a link to the script to generate the icon table in an rST comment could be helpful if the list needs to be generated again.

Thanks for the review and feedback @ccho-mongodb, 

1. 2. I asked in the DOP channel for confirmation on if the screen reader functionality is supported and could not get a conclusive answer. I attempted it on multiple machines and was not able to get it to work so I suspect not. I created [DOP-4123](https://jira.mongodb.org/browse/DOP-4123) to validate that and check on the icons which are not rendering. 

3. I also added a link to a gist with the script for reproducibility.

**Comment by ianf-mongodb** [comment]
Hi @jeff-allen-mongo, @corryroot , @lindseymoore this edit is ready for review whenever you have a moment

**Review by jeff-allen-mongo — APPROVED** [review]
LGTM, just curious how feasible it would be to alphabetize the icons in the table?

**Review by corryroot — APPROVED** [review]
LGTM!

**Review by lindseymoore — APPROVED** [review]
LGTM!

**Comment by ianf-mongodb** [comment]
Thanks for the suggestion @jeff-allen-mongo, I did update the script so now all icons are sorted in alpha order!

**Pull request merged**
